function getInfo() {
	window.numberOfQuestions = 	5;
	window.currentSlide = 		0;
	window.currentScore = 		0;
	window.title = 				"US PRESIDENT TRIVIA";
	window.questions = [		"THE FIRST PRESIDENT OF THE UNITED STATES TO DIE WHILE IN OFFICE WAS", 
								"JOHN WILKES BOOTH SHOUTED THE FOLLOWING LATIN PHRASE AFTER SHOOTING PRESIDENT LINCOLN",
								"THE ONLY PERSON TO SERVE AS BOTH THE PRESIDENT AND ON THE SUPREME COURT WAS", 
								"THE CREATION OF THE INTERSTATE HIGHWAY SYSTEM IS PRIMARILY CREDITED TO", 
								"THE FORMATION OF THE LEAGUE OF NATIONS WAS STRONGLY PROMOTED BY" ];
	window.correctAnswer = [ 	"D", "C", "A", "B", "E" ]; 
	window.answerA = [ 			"ZACHARY TAYLOR", 
								"IN VINO VERITAS", 
								"WILLIAM HOWARD TAFT", 
								"HARRY TRUMAN", 
								"BENJAMIN HARRISON" ];
	window.answerB = [ 			"JAMES K POLK", 
								"E PLURIBUS UNUM", 
								"CALVIN COLLIDGE", 
								"DWIGHT D. EISENHOWER",
								"GROVER CLEVELAND" ];
	window.answerC = [ 			"JOHN TYLER",
								"SIC SEMPER TYRANNIS",
								"WARREN G HARDING", 
								"HERBERT HOOVER", 
								"WILLIAM MCKINLEY" ];
	window.answerD = [ 			"WILLIAM HENRY HARRISON",  
								"ALEA LACTA EST",
								"WOODROW WILSON", 
								"JOHN F KENNEDY",
								"CHESTER A ARTHUR" ];
	window.answerE = [ 			"MARTIN VAN BUREN", 
								"COGITO ERGO SUM", 
								"WILLIAM MCKINLEY", 
								"FRANKLIN DELANO ROOSEVELT", 
								"WOODROW WILSON" ];
	window.response = [ 		"WILLIAM HENRY HARRISON DIED ON APRIL 4, 1841 AFTER ONLY SERVING 30 DAYS IN OFFICE", 
								"SIC SEMPER TYRANNIS ROUGHLY TRANSLATES TO 'THUS ALWAYS TO TYRANTS'", 
								"TAFT WAS STRONGLY ENDORSED FOR THE PRESIDENCY BY THEODORE ROOSEVELT, BUT THE TWO LATER HAD A FALLING OUT", 
								"EISENHOWER MODELED THE US SYSTEM OFF OF THE GERMAN REICHSAUTOBAHN SYSTEM CREATED DURING WORLD WAR II", 
								"THE LEAGUE OF NATIONS LASTED 26 YEARS AND WAS EVENTUALLY REPLACED BY THE UNITED NATIONS" ];
							
}
						